# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
blinker                   1.8.2                    pypi_0    pypi
bzip2                     1.0.8                h5eee18b_6  
ca-certificates           2024.7.2             h06a4308_0  
click                     8.1.7                    pypi_0    pypi
expat                     2.6.2                h6a678d5_0  
flask                     3.0.3                    pypi_0    pypi
itsdangerous              2.2.0                    pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.4                h6a678d5_1  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
markupsafe                2.1.5                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
openssl                   3.0.14               h5eee18b_0  
pip                       24.0            py312h06a4308_0  
python                    3.12.4               h5148396_1  
readline                  8.2                  h5eee18b_0  
setuptools                69.5.1          py312h06a4308_0  
sqlite                    3.45.3               h5eee18b_0  
tk                        8.6.14               h39e8969_0  
tzdata                    2024a                h04d1e81_0  
werkzeug                  3.0.3                    pypi_0    pypi
wheel                     0.43.0          py312h06a4308_0  
xz                        5.4.6                h5eee18b_1  
zlib                      1.2.13               h5eee18b_1  
